blank_issues_enabled: false

contact_links:
  - name: ðŸ’¬ Questions & Discussions
    url: https://github.com/oyanmuhammad/codenight-starter/discussions
    about: Please ask questions or start discussions here.

  - name: ðŸ“– Documentation
    url: https://github.com/oyanmuhammad/codenight-starter
    about: Read the documentation before opening an issue.
